;<VVV-IMPP)ALP TO FIND LARGEST NUMBER IN 8085>
LXI H, 0100H;DATA IN FIRST BLOCK SHOWS THE NUMBER OF DATA IN ADDRESS
MOV C,M;MOVE DATA OF MEMORY IN COUNTER REGISTER C
DCR C; DECREASE THE NUMBER OF COUTER
INX H;INCREMENT OF HL PAIR
MOV A,M;MOVE MEMORY TO ACCUMULATOR
SHLD 0107H;STORE IN MEMORY LOCATION 0107H
LOOP: INX H;INCREMENT OF HL PAIR
		CMP M;COMPARE DATA IN ACCUMULATOR AND MEMORY
		JNC SKIP	
		MOV A,M
		SHLD 0107H;STORE IN MEMORY LOCATION 0107H
SKIP: DCR C;DECREMENT OF LOOP C FROM 4-3-2-1
	JNZ LOOP;
	STA 0109H;STORE LAST VALUE AT 0109H
hlt